### ISSUE TITLE
tomxplayer make error/usr/bin/ld: cannot find -lGLESv2

### ISSUE THREAD

**Issue by jkungjohnson** [Meticulus/tomxplayer#1]
Sir;
i trying to clone tomxplayer into pi jessie stetch desktop lastest version. running raspi-debug with this error:

error/usr/bin/ld: cannot find -lGLESv2

something i miss out ???

**Comment by Meticulus** [comment]
Try removing this line
https://github.com/Meticulus/tomxplayer/blob/master/Makefile#L43

**Comment by Meticulus** [comment]
This should* now be fixed by this commit:

https://github.com/Meticulus/tomxplayer/commit/ea94875352a0cad035b473aa640418cfc15fe6b7
